import streamlit as st
import requests
import plotly.express as px
from fpdf import FPDF

st.set_page_config(page_title="DevTracker Pro", layout="wide")
st.title("🚀 DevTracker Pro v2.0")

username = "on-2008"
st.subheader(f"GitHub: {username}")

# Fetch GitHub Data
try:
    url = f"https://api.github.com/users/{username}"
    res = requests.get(url).json()
    repos = res.get('public_repos', 0)
    followers = res.get('followers', 0)
    following = res.get('following', 0)

    col1, col2, col3 = st.columns(3)
    col1.metric("Repos", repos)
    col2.metric("Followers", followers)
    col3.metric("Following", following)

    # Sample Plotly Chart
    fig = px.bar(x=["Repos", "Followers", "Following"], y=[repos, followers, following], title="GitHub Stats")
    st.plotly_chart(fig)

except Exception as e:
    st.error(f"Error: {e}")

# PDF Function
def create_pdf(g_user):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt=f"GitHub Report for {g_user}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 10, txt=f"Repos: {repos}", ln=True)
    pdf.cell(200, 10, txt=f"Followers: {followers}", ln=True)
    pdf.cell(200, 10, txt="Generated by DevTracker Pro v2.0", ln=True)
    return pdf.output(dest='S').encode('latin-1')

st.divider()
st.subheader("📄 Download Report")
if st.button("Download PDF Report"):
    pdf_bytes = create_pdf(username)
    st.download_button("Download Now", pdf_bytes, file_name="DevTracker_Report.pdf", mime="application/pdf")

st.caption("Built with Streamlit | DevTracker Pro v2.0")
